[package]
name = "nss"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2"
bitflags = "1.0"

[build-dependencies]
bindgen = "0.26"
